package com.example.myrestclient;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.4.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public interface MBNIServiceEvents
{
    void Starting();
    void Completed(MBNOperationResult result);
}
