package com.example.myrestclient;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.4.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class MBNMyServiceBinding
{
    interface MBNIWcfMethod
    {
        MBNExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(MBNExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://10.0.2.2/soap.api.php";

    int timeOut=60000;
    
    public List< HeaderProperty> httpHeaders= new ArrayList< HeaderProperty>();
    public boolean enableLogging;

    MBNIServiceEvents callback;

    public MBNMyServiceBinding(){}

    public MBNMyServiceBinding (MBNIServiceEvents callback)
    {
        this.callback = callback;
    }
    public MBNMyServiceBinding(MBNIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public MBNMyServiceBinding(MBNIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                String path=uri.getPath();
                if(uri.getQuery()!=null && uri.getQuery()!="")
                {
                    path+="?"+uri.getQuery();
                }
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, path, timeOut);
            }
            else
            {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }

    protected MBNExtendedSoapSerializationEnvelope createEnvelope()
    {
        MBNExtendedSoapSerializationEnvelope envelope= new MBNExtendedSoapSerializationEnvelope(MBNExtendedSoapSerializationEnvelope.VER11);
        envelope.enableLogging = enableLogging;
    
        return envelope;
    }

    protected java.util.List sendRequest(String methodName,MBNExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport ,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile )throws java.lang.Exception
    {
        if(transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE )
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
        else
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,MBNExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) 
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }

        return null;
    }

    
    
    
    public Boolean CreatePerson(final String Name,final Integer Age,final String Mail,final Integer LanguageID) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Boolean)execute(new MBNIWcfMethod()
        {
            @Override
            public MBNExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                MBNExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://localhost/", "CreatePerson_Request");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://localhost/";
                __info.name="Name";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(Name);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://localhost/";
                __info.name="Age";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(Age);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://localhost/";
                __info.name="Mail";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(Mail);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://localhost/";
                __info.name="LanguageID";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(LanguageID);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MBNExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("state");
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return Boolean.valueOf(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, MBNOperationResult< Boolean>> CreatePersonAsync(final String Name,final Integer Age,final String Mail,final Integer LanguageID)
    {
        return executeAsync(new MBNFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return CreatePerson( Name,Age,Mail,LanguageID);
            }
        },"CreatePerson");
    }
    
    
    
    public MBNListPeople_Response ListPeople() throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (MBNListPeople_Response)execute(new MBNIWcfMethod()
        {
            @Override
            public MBNExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                MBNExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://localhost/", "ListPeople_Request");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MBNExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MBNListPeople_Response)getResult(MBNListPeople_Response.class,__result,"ListPeople_Response",__envelope);
            }
        },"",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, MBNOperationResult< MBNListPeople_Response>> ListPeopleAsync()
    {
        return executeAsync(new MBNFunctions.IFunc< MBNListPeople_Response>() {
            public MBNListPeople_Response Func() throws java.lang.Exception {
                return ListPeople( );
            }
        },"ListPeople");
    }
    
    
    
    public MBNSOAP_Person ReadPerson(final Integer ID) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (MBNSOAP_Person)execute(new MBNIWcfMethod()
        {
            @Override
            public MBNExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                MBNExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://localhost/", "ReadPerson_Request");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://localhost/";
                __info.name="ID";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(ID);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MBNExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MBNSOAP_Person)getResult(MBNSOAP_Person.class,__result,"Person",__envelope);
            }
        },"",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, MBNOperationResult< MBNSOAP_Person>> ReadPersonAsync(final Integer ID)
    {
        return executeAsync(new MBNFunctions.IFunc< MBNSOAP_Person>() {
            public MBNSOAP_Person Func() throws java.lang.Exception {
                return ReadPerson( ID);
            }
        },"ReadPerson");
    }
    
    
    
    public Boolean UpdatePerson(final Integer ID,final String Name,final Integer Age,final String Mail,final Integer LanguageID) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Boolean)execute(new MBNIWcfMethod()
        {
            @Override
            public MBNExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                MBNExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://localhost/", "UpdatePerson_Request");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://localhost/";
                __info.name="ID";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(ID);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://localhost/";
                __info.name="Name";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(Name);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://localhost/";
                __info.name="Age";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(Age);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://localhost/";
                __info.name="Mail";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(Mail);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://localhost/";
                __info.name="LanguageID";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(LanguageID);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MBNExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("state");
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return Boolean.valueOf(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, MBNOperationResult< Boolean>> UpdatePersonAsync(final Integer ID,final String Name,final Integer Age,final String Mail,final Integer LanguageID)
    {
        return executeAsync(new MBNFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return UpdatePerson( ID,Name,Age,Mail,LanguageID);
            }
        },"UpdatePerson");
    }
    
    
    
    public Boolean DeletePerson(final Integer ID) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Boolean)execute(new MBNIWcfMethod()
        {
            @Override
            public MBNExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                MBNExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://localhost/", "DeletePerson_Request");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://localhost/";
                __info.name="ID";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(ID);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MBNExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("state");
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return Boolean.valueOf(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, MBNOperationResult< Boolean>> DeletePersonAsync(final Integer ID)
    {
        return executeAsync(new MBNFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return DeletePerson( ID);
            }
        },"DeletePerson");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String ListLanguages() throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public android.os.AsyncTask< Void, Void, MBNOperationResult< String>> ListLanguagesAsync()
    {
        return executeAsync(new MBNFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return ListLanguages( );
            }
        },"ListLanguages");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String CreateLanguage(final String Name) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public android.os.AsyncTask< Void, Void, MBNOperationResult< String>> CreateLanguageAsync(final String Name)
    {
        return executeAsync(new MBNFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CreateLanguage( Name);
            }
        },"CreateLanguage");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String ReadLanguage(final String ID) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public android.os.AsyncTask< Void, Void, MBNOperationResult< String>> ReadLanguageAsync(final String ID)
    {
        return executeAsync(new MBNFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return ReadLanguage( ID);
            }
        },"ReadLanguage");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String UpdateLanguage(final String ID,final String Name) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public android.os.AsyncTask< Void, Void, MBNOperationResult< String>> UpdateLanguageAsync(final String ID,final String Name)
    {
        return executeAsync(new MBNFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return UpdateLanguage( ID,Name);
            }
        },"UpdateLanguage");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String DeleteLanguage(final String ID) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public android.os.AsyncTask< Void, Void, MBNOperationResult< String>> DeleteLanguageAsync(final String ID)
    {
        return executeAsync(new MBNFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return DeleteLanguage( ID);
            }
        },"DeleteLanguage");
    }

    protected java.lang.Object execute(MBNIWcfMethod wcfMethod,String methodName,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        MBNExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport,profile);
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }

    protected < T> android.os.AsyncTask< Void, Void, MBNOperationResult< T>>  executeAsync(final MBNFunctions.IFunc< T> func, final String methodName)
    {
        return new android.os.AsyncTask< Void, Void, MBNOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            }
            @Override
            protected MBNOperationResult< T> doInBackground(Void... params) {
                MBNOperationResult< T> result = new MBNOperationResult< T>();
                try
                {
                    result.MethodName=methodName;
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(MBNOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }

    protected java.lang.Exception convertToException(org.ksoap2.SoapFault fault,MBNExtendedSoapSerializationEnvelope envelope)
    {
        org.ksoap2.SoapFault newException = fault;
        return newException;
    }
}


