package com.example.myrestclient;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.4.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public class MBNOperationResult< T>
{
    
    public java.lang.Exception Exception;
    
    public T Result;
    
    public java.lang.Object Tag;
    
    public java.lang.String MethodName;
}
