package com.example.myrestclient;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.4.0
//
// Created by Quasar Development 
//
//----------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public  class MBNSOAP_Person extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    public Integer ID=0;
    
    public String Name;
    
    public Integer Age=0;
    
    public String Mail;
    
    public Integer LanguageID=0;
    
    public String Language;

    

    public void loadFromSoap(java.lang.Object paramObj,MBNExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }


    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,MBNExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("ID"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ID = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.ID = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Name"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Name = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Name = (String)obj;
                }
                else{
                    this.Name = "";
                }
            }
            return true;
        }
        if (info.name.equals("Age"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Age = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.Age = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Mail"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Mail = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Mail = (String)obj;
                }
                else{
                    this.Mail = "";
                }
            }
            return true;
        }
        if (info.name.equals("LanguageID"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.LanguageID = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.LanguageID = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Language"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Language = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Language = (String)obj;
                }
                else{
                    this.Language = "";
                }
            }
            return true;
        }
        return false;
    }    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    
    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.ID;
        }
        else if(propertyIndex==1)
        {
            return this.Name;
        }
        else if(propertyIndex==2)
        {
            return this.Age;
        }
        else if(propertyIndex==3)
        {
            return this.Mail;
        }
        else if(propertyIndex==4)
        {
            return this.LanguageID;
        }
        else if(propertyIndex==5)
        {
            return this.Language!=null?this.Language:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
            if(propertyIndex==0)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "ID";
                info.namespace= "http://localhost/";
            }
            else if(propertyIndex==1)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Name";
                info.namespace= "http://localhost/";
            }
            else if(propertyIndex==2)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "Age";
                info.namespace= "http://localhost/";
            }
            else if(propertyIndex==3)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Mail";
                info.namespace= "http://localhost/";
            }
            else if(propertyIndex==4)
            {
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "LanguageID";
                info.namespace= "http://localhost/";
            }
            else if(propertyIndex==5)
            {
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Language";
                info.namespace= "http://localhost/";
            }
}

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
